services:
  db:
    image: bitnami/postgresql:15.4.0
    container_name: postgres_db_emailn
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=emailn_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=emailn
    volumes:
      - emailn_db_data:/bitnami/postgresql

volumes:
  emailn_db_data: